FROM ubuntu:16.04

RUN apt update && apt install -y python3 python3-pip

WORKDIR /usr/src/app

ADD requirements.txt .

RUN pip3 install -r requirements.txt

COPY . /usr/src/app

ENV EMAIL_PASSWD=""
ENV DB_HOST=""
ENV DB_NAME=""
ENV DB_USER=""
ENV DB_PASSWD=""
ENV PORT=8000
ENV ADMINS=""
ENV NUM_PAPERS_PER_RUN=10
ENV AFP_BASE_URL="http://textpressocentral.org:3000"

EXPOSE ${PORT}
CMD python3 db_api.py -N ${DB_NAME} -U ${DB_USER} -P "${DB_PASSWD}" -H ${DB_HOST} -p ${PORT} -a ${ADMINS} -e ${EMAIL_PASSWD} -u ${AFP_BASE_URL} -l /var/log/afp_db_api.log -L DEBUG