FROM node:8.2.1
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY src/frontend/submission_form .
RUN npm install --silent
COPY . /usr/src/app

# development environment
EXPOSE 3000
CMD ["npm", "start"]